#!/usr/bin/env python3
"""
new_part.py -- scaffold a model + its matching bench recipe.

Writing the boilerplate by hand costs tokens and gets the params-json
round-trip subtly wrong. Run this instead, then edit only `derive()`,
`build()` and the recipe's `checks`/`draw`.

    python scripts/new_part.py --name spacer_plate \
        --params "plate_x=90,plate_y=50,plate_t=4,bore_d=30,hole_d=4.5,inset=8"

Writes:
    models/<name>.py                a runnable model (builds a placeholder box)
    models/<name>.recipe.js         a PARTS entry to paste into the bench

Both are already wired: identical parameter names, params-json override,
verification, and a `main()` that runs. Confirm it runs before you edit it --
then replace the marked sections.
"""

import argparse
import os
import re

MODEL = '''#!/usr/bin/env python3
"""{name} -- generated by scripts/new_part.py, then edited.

<one line: what this part is and what it mates with>
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "scripts"))
import brep as B

PARAMS = {{
{params}
}}


def derive(P):
    """Computed values. Mirror this in the bench recipe's derive()."""
    d = dict(P)
    # TODO derived quantities -- wall thicknesses, positions, radii.
    return d


def build(P):
    d = derive(P)
    # TODO replace this placeholder with the real feature tree.
    # Order that avoids most failures:
    #   1 solid outer form  2 fillet  3 shell (offset+openings)
    #   4 chamfer (outer_of() on a rim)  5 internal features  6 bores/ports
    part = B.Box({first}, {first}, {first},
                 align=(B.Align.CENTER, B.Align.CENTER, B.Align.MIN))
    return part


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    P = dict(PARAMS)
    over = os.path.join(here, "{name}.params.json")
    if os.path.exists(over):
        with open(over) as fh:
            P.update({{k: float(v) for k, v in json.load(fh).items() if k in PARAMS}})
        print(f"loaded overrides from {{os.path.basename(over)}}")

    d = derive(P)
    part = build(P)

    # TODO assert the dimensions a bounding box cannot see.
    # B.wall_check("boss wall", d["boss_wall"], 1.2)

    if B.solid_count(part) != 1:
        raise B.VerifyError(f"{name}: {{B.solid_count(part)}} solids, expected 1")

    B.export_verified(part, os.path.join(here, "{name}.stl"), "{name}")


if __name__ == "__main__":
    main()
'''

RECIPE = '''// Paste this into the PARTS object in the CAD Bench artifact, then run
//   python scripts/check_bench.py <bench.html>
// to confirm it renders without NaN at every slider extreme.
"{key}":{{
  label:"{label}", file:"models/{name}.py",
  note:"<why the dimensions are what they are -- the reasoning a reviewer needs>",
  params:[
{sliders}
  ],
  derive(p){{
    // Mirror models/{name}.py derive(). Slider values are on `p`;
    // computed values on `d`. Reading `d.<a slider name>` yields NaN.
    return {{
      // TODO
    }};
  }},
  cards:d=>[
    // ["Label", d.value.toFixed(2)],
  ],
  checks(p,d){{
    return [
      // [p.a >= p.b, "Claim about the part", p.a.toFixed(2)+" of "+p.b],
    ];
  }},
  draw(p,d){{
    const o=[];
    const s=Math.min(300/{first}, 210/{first});
    const cx=26+{first}/2*s, cy=132;
    const T=(x,y)=>[cx+x*s, cy-y*s];
    o.push(cap(24,20,"TOP VIEW"));
    // TODO real geometry: rc() rects, ci() holes, pg() polygons, ln() datums
    o.push(rc(...T(-{first}/2, {first}/2), {first}*s, {first}*s));
    return o.join("");
  }}
}},
'''


def parse_params(text):
    out = []
    for chunk in text.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "=" not in chunk:
            raise SystemExit(f"bad --params entry {chunk!r}, expected name=value")
        k, v = chunk.split("=", 1)
        k = k.strip()
        if not re.fullmatch(r"[a-z_][a-z0-9_]*", k):
            raise SystemExit(f"parameter {k!r} must be lower_snake_case "
                             "(it becomes both a Python key and a slider id)")
        out.append((k, float(v)))
    if not out:
        raise SystemExit("--params must define at least one parameter")
    return out


def slider(k, v):
    """A sane starting range: half to double, clamped away from zero."""
    lo = round(max(v * 0.5, 0.1), 2) if v > 0 else 0.0
    hi = round(max(v * 2.0, v + 1.0), 2)
    step = 0.1 if v < 10 else (0.5 if v < 60 else 1)
    label = k.replace("_", " ").capitalize()
    return (f'    {{id:"{k}",fs:"{k.upper()}",u:"MM",g:"Main",'
            f'label:"{label}",min:{lo},max:{hi},step:{step},val:{v:g}}}')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True,
                    help="lower_snake_case, e.g. spacer_plate")
    ap.add_argument("--params", required=True,
                    help='comma separated name=value, e.g. "w=90,d=50,t=4"')
    ap.add_argument("--label", default=None, help="human name for the picker")
    a = ap.parse_args()

    if not re.fullmatch(r"[a-z_][a-z0-9_]*", a.name):
        raise SystemExit("--name must be lower_snake_case")

    params = parse_params(a.params)
    first = f"{params[0][1]:g}"
    label = a.label or a.name.replace("_", " ").capitalize()
    key = a.name.replace("_", "-")

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    models = os.path.join(root, "models")
    os.makedirs(models, exist_ok=True)

    mp = os.path.join(models, f"{a.name}.py")
    rp = os.path.join(models, f"{a.name}.recipe.js")
    for p in (mp, rp):
        if os.path.exists(p):
            raise SystemExit(f"{p} already exists -- refusing to overwrite")

    with open(mp, "w", encoding="utf-8") as fh:
        fh.write(MODEL.format(
            name=a.name, first=first,
            params="\n".join(f'    "{k}": {v!r},' for k, v in params)))
    with open(rp, "w", encoding="utf-8") as fh:
        fh.write(RECIPE.format(
            key=key, label=label, name=a.name, first=first,
            sliders=",\n".join(slider(k, v) for k, v in params)))

    print(f"wrote {mp}")
    print(f"wrote {rp}")
    print(f"\nnext: run it as-is to confirm the harness works --")
    print(f"    python models/{a.name}.py")
    print("then replace derive()/build() and the recipe's checks()/draw().")


if __name__ == "__main__":
    main()
